# Generated by Django 3.2.8 on 2021-10-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('subtype', models.CharField(max_length=15, null=True)),
                ('fees', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='upload',
            name='phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='upload',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload', to='uploadapp.feesdata'),
        ),
    ]
