# Generated by Django 3.2.8 on 2021-10-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_auto_20211010_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='type',
        ),
        migrations.DeleteModel(
            name='FeesData',
        ),
    ]
